{% set name = "pixi" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/prefix-dev/pixi/archive/refs/tags/v{{ version }}.tar.gz
  sha256: af2092bbe1bfd480f5e187c361da234965276d2eef4e00dc393b30c2ad05f168

build:
  number: 0
  # disable binary prefix detection, because rattler-build encodes the old `anaconda1anaconda2anaconda3` prefix
  # somewhere to make old packages installable. In other words, conda-build finds a false-positive here.
  detect_binary_files_with_prefix: false

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    # to compile the libsolv parts
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - cmake
    - make  # [unix]
  host:
    - openssl  # [linux]

test:
  commands:
    - pixi --help

about:
  home: https://github.com/prefix-dev/pixi
  summary: pixi is a cross-platform, multi-language package manager and workflow tool build on the shoulders of the conda ecosystem.
  description: |
    pixi is a cross-platform, multi-language package manager and workflow tool build on the shoulders of the conda ecosystem.

    pixi provides all developers the exceptional experience that is usually found with package managers like cargo or yarn but for any language.

    # Highlights

    - Support for multiple languages like Python, C++ and R using Conda packages
    - All OS's: Linux, Windows, macOS (including Apple Silicon)
    - A lockfile is always included and always up-to-date.
    - A clean and simple Cargo-like command-line interface.
    - Install tools per-project or system-wide.
    - Completely written in Rust and build on top of the rattler library.

  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - wolfv
    - baszalmstra
    - tdejager
    - ruben-arts
