schema_version: 1

context:
  name: pixi
  version: "0.41.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/prefix-dev/pixi/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 9926d31fc524867f989285bb8f4d09f28750224437c0351dd237de75af2b2fb8

build:
  number: 1

  script:
    env:
      # This env var  specifies the base 2 log of the allocator page size
      JEMALLOC_SYS_WITH_LG_PAGE: ${{ "16" if target_platform == "linux-aarch64" or target_platform == "linux-ppc64le" }}
      OPENSSL_DIR: ${{ prefix }}
    interpreter: nu
    content: |
        cargo install --locked --bins --root $env.PREFIX --path . --no-track
        cargo-bundle-licenses --format yaml --output $"($env.SRC_DIR)/THIRDPARTY.yml"



requirements:
  build:
    - nushell
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    # to compile the libsolv parts
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - pkg-config
    - cmake
    - if: unix
      then: make
  host:
    - if: linux
      then: openssl
    - if: win
      then: libgit2

tests:
  - script:
      - pixi --help

about:
  summary: pixi is a cross-platform, multi-language package manager and workflow tool build on the shoulders of the conda ecosystem.
  description: |
    pixi is a cross-platform, multi-language package manager and workflow tool build on the shoulders of the conda ecosystem.

    pixi provides all developers the exceptional experience that is usually found with package managers like cargo or yarn but for any language.

    # Highlights

    - Support for multiple languages like Python, C++ and R using Conda packages
    - All OS's: Linux, Windows, macOS (including Apple Silicon)
    - A lockfile is always included and always up-to-date.
    - A clean and simple Cargo-like command-line interface.
    - Install tools per-project or system-wide.
    - Completely written in Rust and build on top of the rattler library.

  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/prefix-dev/pixi

extra:
  recipe-maintainers:
    - wolfv
    - baszalmstra
    - tdejager
    - ruben-arts
    - Hofer-Julian
